apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: django-deployment
  labels: 
    app: django-deployment 
    type: backend 
spec: 
  replicas: 5
  selector: 
    matchLabels: 
      app: django-deployment  
      type: backend
  template: 
    metadata: 
      labels: 
        app: django-deployment 
        type: backend 
    spec:  
      containers: 
      - name: python-app
        image: abhishekf5/python-sample-app-demo:v1
        ports: 
        - containerPort: 8000 

---
apiVersion: v1
kind: Service
metadata: 
  name: django-service 
spec: 
  type: NodePort 
  selector: 
    app: django-deployment 
    type: backend 
  ports: 
  - port: 80 
    targetPort: 8000 
    nodePort: 30007  

---
apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: first-ingress
spec: 
  rules: 
  - host: "foo.bar.com"
    http: 
      paths: 
      - pathType: Prefix 
        path: "/bar"
        backend: 
          service: 
            name: django-service  # mention your service name 
            port:   
              number: 80